services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./etc:/usr/local/etc:ro

  motion:
    build:
      dockerfile: Dockerfile-motion
    command: motion -n
    depends_on:
      - redis
    volumes:
      - ./data:/data
      - ./log:/var/log
      - ./etc:/usr/local/etc:ro
    environment:
      - REDIS_URL=redis://redis

  io:
    build: 
      context: .
      dockerfile: Dockerfile-io
    command: ./watchutil.py ioworker 2>&1 | tee -a /var/log/io-worker.log
    depends_on:
      - redis
    volumes:
      - ./data:/data
      - ./log:/var/log
      - ./etc:/usr/local/etc:ro
    environment:
      - WATCHER_CONFIG=/usr/local/etc/watcher.cfg

  video:
    #image: watcher
    build: 
      context: .
      dockerfile: Dockerfile-video
    command: ./watchutil.py videoworker 2>&1 | tee -a /var/log/video-worker.log
    depends_on:
      - redis
      - motion
    volumes:
      - ./data:/data
      - ./log:/var/log
      - ./etc:/usr/local/etc:ro
    environment:
      - WATCHER_CONFIG=/usr/local/etc/watcher.cfg


  # api:
  #   build: .
  #   profiles: ["api"]
  #   command: uwsgi --http 127.0.0.1:8000 --master -p 4 -w api:app
  #   ports:
  #     - 127.0.0.1:80:8000
  #     #- 127.0.0.1:443:443
  #   volumes:
  #     - ./data:/data
  #     - ./log:/var/log
  #     - ./etc:/usr/local/etc:ro
    
  static-web:
    image: nginx
    profiles: ["web"]
    volumes:
     - ./data/video:/data/video:ro
     - ./etc/nginx:/etc/nginx:ro
    ports:
     - "8080:80"
    environment:
     - NGINX_HOST=mira.local
     - NGINX_PORT=80
