services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./etc:/usr/local/etc:ro
    restart: always

  motion:
    build:
      dockerfile: Dockerfile-motion
    command: motion -n
    depends_on:
      - redis
    volumes:
      - ./data:/data
      - ./log:/var/log
    environment:
      - REDIS_URL=redis://redis
    restart: always

  io:
    build: 
      context: .
      dockerfile: Dockerfile-io
    command: ./watchutil.py ioworker
    depends_on:
      - redis
    volumes:
      - ./data:/data
      - ./log:/var/log
    environment:
      - WATCHER_CONFIG=/usr/local/etc/watcher.cfg
      - WATCHER_LOG_FILE=/var/log/watcher/ioworker.log
    restart: always

  video:
    build:
      context: .
      dockerfile: Dockerfile-video
    command: ./watchutil.py videoworker
    depends_on:
      - redis
    volumes:
      - ./data:/data
      - ./log:/var/log
    environment:
      - WATCHER_CONFIG=/usr/local/etc/watcher.cfg
      - WATCHER_LOG_FILE=/var/log/watcher/videoworker.log
    restart: always

  predictor:
    profiles: ["predictor", "all"]
    build:
      context: .
      dockerfile: Dockerfile-predictor
    command: ./watchutil.py predictionworker
    depends_on:
      - redis
    volumes:
      - ./data:/data
      - ./log:/var/log
    environment:
      - WATCHER_CONFIG=/usr/local/etc/watcher.cfg
      - WATCHER_LOG_FILE=/var/log/watcher/predictor.log
    restart: always
   
  api:
    build: 
      context: .
      dockerfile: Dockerfile-api
    profiles: ["web", "all"]
    command: uwsgi --ini /usr/local/etc/uwsgi.ini
    volumes:
      - ./data:/data
      - ./log:/var/log
    environment:
      - WATCHER_CONFIG=/usr/local/etc/watcher.cfg
      - WATCHER_LOG_FILE=/var/log/watcher/api.log
    restart: always
    
  web:
    image: nginx
    profiles: ["web", "all"]
    volumes:
     - ./data/video:/data/video:ro
     - ./etc/nginx:/etc/nginx:ro
    ports:
     - "80:80"
    environment:
     - NGINX_HOST=mira.local
     - NGINX_PORT=80
    restart: always
