services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./etc:/usr/local/etc:ro
    restart: always

  motion:
    build:
      dockerfile: Dockerfile-motion
    command: motion -n
    depends_on:
      - redis
    volumes:
      - ./data:/data
      - ./log:/var/log
      - ./etc:/usr/local/etc:ro
    environment:
      - REDIS_URL=redis://redis
    restart: always

  io:
    build: 
      context: .
      dockerfile: Dockerfile-io
    command: ./watchutil.py ioworker
    depends_on:
      - redis
    volumes:
      - ./data:/data
      - ./log:/var/log
      - ./etc:/usr/local/etc:ro
    environment:
      - WATCHER_CONFIG=/usr/local/etc/watcher.cfg
    restart: always

  video:
    build:
      context: .
      dockerfile: Dockerfile-video
    command: ./watchutil.py videoworker
    depends_on:
      - redis
    volumes:
      - ./data:/data
      - ./log:/var/log
      - ./etc:/usr/local/etc:ro
    environment:
      - WATCHER_CONFIG=/usr/local/etc/watcher.cfg

  predictor:
    profiles: ["predictor"]
    build:
      context: .
      dockerfile: Dockerfile-predictor
    command: ./watchutil.py predictionworker
    depends_on:
      - redis
    volumes:
      - ./data:/data
      - ./log:/var/log
      - ./etc:/usr/local/etc:ro
    environment:
      - WATCHER_CONFIG=/usr/local/etc/watcher.cfg
   
  api:
    build: 
      context: .
      dockerfile: Dockerfile-io
    profiles: ["web"]
    command: uwsgi --ini /usr/local/etc/uwsgi.ini
    volumes:
      - ./data:/data
      - ./log:/var/log
      - ./etc:/usr/local/etc:ro
    environment:
      - WATCHER_CONFIG=/usr/local/etc/watcher.cfg
    
  web:
    image: nginx
    profiles: ["web"]
    volumes:
     - ./data/video:/data/video:ro
     - ./etc/nginx:/etc/nginx:ro
    ports:
     - "80:80"
    environment:
     - NGINX_HOST=mira.local
     - NGINX_PORT=80
