FROM camera-watcher-io

## OS dependencies

RUN apt-get update
RUN apt-get -y install libgl-dev --fix-missing
RUN apt-get -y install ffmpeg

## python requirements
WORKDIR /app
COPY requirements-video.txt ./
RUN python3 -m pip install -r requirements-video.txt

## source dependencies

WORKDIR /app

RUN mkdir -p /app/camera-watcher
WORKDIR /app/camera-watcher

COPY *.py ./
COPY watcher watcher/

COPY ./etc/watcher.cfg /usr/local/etc/watcher.cfg